
service: my-money-sfm
# Use serverless-webpack plugin to transpile ES6/ES7
package:
  exlude:
    - node_modules/aws-sdk/**
    - node_modules/mocha/**

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    USER_TABLE: myMoney
  stage: dev
  region: us-east-1

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:

  # alexa skill handler
  skill:
    handler: alexa/index.handler
    events:
      - alexaSkill

  list:
    handler: users/list.list
    events:
      - http:
          path: users
          method: get
          cors: true
  get:
    handler: users/get.get
    events:
      - http:
          path: users/{userID}
          method: get
          cors: true
